name: a08_read_json_data demo 
description: Demo showing how to read a json file attached to caller workflow repo using two methods
# 1. directly in shell using jq
# 2. in javascript using another action

inputs:
  file_path:
    required: true 
    type: string
outputs:
  data:
    description: "json data"
    value: ${{ steps.read_json.outputs.result }} 
runs:
  using: "composite"
  steps:
    - name: checkout file
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          ${{inputs.file_path}}
        sparse-checkout-cone-mode: false  
    - name: read json directly in shell
      shell: bash
      run: |
       myvar=$(jq '.' ${{ github.workspace }}/${{inputs.file_path}})
       echo $myvar | jq '.level0.level1.level2'
       myvar=$(jq '.level0.level1.level2.level3' ${{ github.workspace }}/${{inputs.file_path}})
       echo $myvar | jq '.'
    - name: call the javascript action to read a json file
      uses: actions/github-script@v7
      id: read_json
      with:
      # comment the following to get json output result
      # result-encoding: string
        script: |
          try {
            const fs = require('fs')
            const jsonString = fs.readFileSync('${{ github.workspace }}/${{inputs.file_path}}')
            var data = JSON.parse(jsonString)
            // console.log(data)
            // console.log(data.level0.level1.level2.level3.level4.list)
            return data
          } catch(err) {
            core.error("Error json data")
            core.setFailed(err)
          }
