name: a07_scripts action
description: call a script in the same repo as this action, with script path given relative to repo root
inputs:
  bash_script:
    required: true 
    type: string    
  py_script:
    required: true 
    type: string
  js_script:
    required: true 
    type: string  
runs:
  using: "composite"
  steps:
    - name: run a bash script
      shell: bash
      # The first two commands are anonymous, they run the script in the current shell, changes in environment sustain (e.g changing directory or defining env vars),
      # and the script does not need to be executable in the first two commands.
      # The third command (chmod ...) is required to run the fourth command which runs the  script in a new shell and any environmental changes made inside the 
      # script are not propagated to the current shell.
      run: |
        source ${{github.action_path}}/../../${{inputs.bash_script}}
        . ${{github.action_path}}/../../${{inputs.bash_script}}
        chmod +x ${{github.action_path}}/../../${{inputs.bash_script}}
        ${{github.action_path}}/../../${{inputs.bash_script}}
    - name: Set up Python 
      shell: bash
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: run a python script
      run: python ${{github.action_path}}/../../${{inputs.py_script}}
    - name: run a js script
      uses: actions/github-script@v7
      with:
        script: |
          try {
            const exec = require('${{github.action_path}}/../../${{inputs.js_script}}')
            exec()          
            return "success"
          } catch(err) {
            core.error("Error json data")
            core.setFailed(err)
          }


