name: a08_read_yaml_data demo
description: Demo showing how to read a yaml file located in the caller workflow repo using two methods
# 1. directly in shell using yq
# 2. using javascript action: actions/github-script

inputs:
  file_path:
    required: true 
    type: string
outputs:
  data:
    description: "json data"
    value: ${{ steps.read_file.outputs.result }} 
runs:
  using: "composite"
  steps:
    - name: checkout file
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          ${{inputs.file_path}}
        sparse-checkout-cone-mode: false  
    - name: read json directly in shell
      shell: bash
      run: |
        myvar=$(yq '.level0.level1.level2.level3.level4.list[0]' ${{ github.workspace }}/${{inputs.file_path}})
        echo $myvar
    - name: install js-yaml
      shell: bash
      run: npm install js-yaml
    - name: call the javascript action to read the file
      uses: actions/github-script@v7
      id: read_file
      with:
        script: |
          try {
            const yml = require('js-yaml')
            const fs = require('fs')
            const data = yml.load(fs.readFileSync('${{ github.workspace }}/${{inputs.file_path}}'))
            // var data = JSON.parse(jsonString)
             console.log(data)
             console.log(data.level0.level1.level2.level3.level4.list)
            return data
          } catch(err) {
            core.error("Error json data")
            core.setFailed(err)
          }
