name: rw04_inputs_outputs a reusable workflow with inputs and outputs 
on:
  workflow_call:
    inputs:
      input1:
        required: true  # if 'required' is 'false', set a default value using default: somevalue
        type: string 
      input2:
        required: true  # if 'required' is 'false', set a default value using default: somevalue
        type: string
    outputs:
      an_output:
        description: "An output"
        value: ${{ jobs.set_outputs.outputs.output1 }}
      another_output:
        description: "Another output"
        value: ${{ jobs.set_outputs.outputs.output2 }}
jobs:
  set_outputs:
    name: Generate output
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.output1 }}
      output2: ${{ steps.step2.outputs.output2 }}
    steps:
      - id: step1
        run: echo "output1=output base on ${{inputs.input1}}" >> $GITHUB_OUTPUT
      - id: step2
        run: echo "output2=output based on ${{inputs.input2}}" >> $GITHUB_OUTPUT
  print_to_console: # just verify inputs and outputs
   name: print inputs and ouputs
   runs-on: ubuntu-latest
   needs: [set_outputs]
   steps:
    - run: echo '${{ toJSON(inputs) }}'
    - run: echo '${{ toJSON(needs.set_outputs.outputs) }}'
    - run: echo done with reusable workflow
