name: rw06_secrets_vars using secrets and variables in a reusable workflow
on:
  workflow_call:
    secrets: # reusable workflows do not have direct access to secrets, we have to pass them from the caller
      repo_s:
        required: true
      org_s:
        required: true
jobs:
  use_secrets_and_vars:
    runs-on: ubuntu-latest
    steps:
      - run: ${{secrets.org_s=='orgsecret'}}  | sed 's/./& /g' # prints the secret for test; use only for a dummy secret.
      - run: echo ${{secrets.org_s}} | sed 's/./& /g' # prints the secret for test; use only for a dummy secret.
      # the variables defined at the repository or organization level will be available in called workflow
      # We do not need to pass these vars from the caller workflow.
      - run: echo ${{vars.repo_var}} # a variable defined at the repository level
      - run: echo ${{vars.org_var}} # a variable defined at the organization level
      - run: echo reusable workflow done
