name: rw06_secrets_vars using secrets and variables in a reusable workflow
on:
  workflow_call:
    secrets: # reusable workflows do not have direct access to secrets, we have to pass them from the caller
      repo_s:
        required: true
      org_s:
        required: true
jobs:
  use_secrets_and_vars:
    runs-on: ubuntu-latest
    steps:
    # the sed 's/./& /g' is used to unmask asecret, use it only for dummy secrets
      - run: |
          ${{secrets.org_s=='orgsecret'}}  | sed 's/./& /g'
          echo ${{secrets.org_s}} | sed 's/./& /g' 
          echo ${{vars.repo_var}} # a variable defined at the repository level
          echo ${{vars.org_var}} # a variable defined at the organization level
          echo reusable workflow done
