name: rw07 run scripts 
on:
  workflow_call:
    inputs:
      bash_script:
        required: true 
        type: string  
      py_script:
        required: true 
        type: string
      js_script:
        required: true 
        type: string  
jobs:
  job1:
    name: run scripts
    runs-on: ubuntu-latest
    steps:
      - name: checkout file
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            source ${{inputs.bash_script}}
      # cone mode false means will checkout only the file/files mentioned in the path
      # default is true which checks out repository root level files unnecessarily for our case
          sparse-checkout-cone-mode: false 
      - name: run scripts
        run: |
          ${{ github.workspace }}/${{inputs.bash_script}}
          echo reusable workflow done
