name: rw07 run scripts 
on:
  workflow_call:
    inputs:
      bash_script:
        required: true 
        type: string  
      py_script:
        required: true 
        type: string
      js_script:
        required: true 
        type: string  
jobs:
  job1:
    name: run scripts
    runs-on: ubuntu-latest
    steps:
      - name: checkout file
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            ${{inputs.bash_script}}
            ${{inputs.py_script}}
            ${{inputs.js_script}}
      # cone mode false means will checkout only the file/files mentioned in the path
      # default is true which checks out repository root level files unnecessarily for our case
          sparse-checkout-cone-mode: false 
      - name: run a bash script
        run: |
          chmod +x ${{ github.workspace }}/${{inputs.bash_script}}
          ${{ github.workspace }}/${{inputs.bash_script}}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: run a python script
        run: python ${{ github.workspace }}/${{inputs.py_script}}
      - name: run a js script
        uses: actions/github-script@v7
        with:
      # comment the following to get json output result
      # result-encoding: string
          script: ${{ github.workspace }}/${{inputs.js_script}}()
            
        
